# Generated by Django 3.1 on 2020-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='livesite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
