# Generated by Django 3.1 on 2020-09-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
