# Generated by Django 3.1.1 on 2020-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200909_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outside_livesite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
